# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c28dcd88cbd5a2506e137bd321aa6d07630e157b00766d6d7b84b7a44d577477f3b9877adaca1e83c0efa09962ca102b79c925faf748019631c9d8ebf4e7b630

test:
  secret_key_base: d9facdf8e1a19cb816c11785566a428f5cd027febd59ac6317bb8b0a5cbb13f4204397f6a4e6a2e589ed38657e6eb55b01422f13386d4a56524c85eb825b4fab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
